---
# tasks file for PM2
- name: Install "pm2" node.js package globally.
  npm:
    name: pm2
    global: yes
    state: present

- name: change file content with "lineinfile"
  lineinfile:
    dest: /usr/local/lib/node_modules/pm2/bin/pm2
    regexp: '\/usr\/bin\/env node'
    line: '#!/usr/bin/env nodejs'
