---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Install and run gify-panda, counter-panda services against mentioned hosts
  hosts: base
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: forever, tags: forever }
    - { role: gify-panda, tags: gify-panda }
    - { role: counter-panda, tags: counter-panda }
